In [ ]:
Time (h) Temperature (°C) Voltage (V) Current (A) Charge (%)
0 32 400 20 95
1 35 395 22 88
2 38 390 25 80
3 40 385 28 70
4 42 380 30 60
5 45 375 32 48

In [ ]:
d={
    "h":[0,1,2,3,4,5],"c":[32,35,38,40,42,45],"v":[400,395,390,385,380,375],"a":[20,22,25,28,30,32],"e":[95,88,80,70,60,48]
}


In [ ]:
for j in range(6):
  print(d["h"][j],d["c"][j],d["v"][j],d["a"][j],d["e"][j])

0 32 400 20 95
1 35 395 22 88
2 38 390 25 80
3 40 385 28 70
4 42 380 30 60
5 45 375 32 48


In [ ]:
for j in range(6):
  if(d["c"][j]>40):
    print("High Temperature Alert")
  else:
    print("Temperature Normal")


Temperature Normal
Temperature Normal
Temperature Normal
Temperature Normal
High Temperature Alert
High Temperature Alert


In [ ]:
for j in range(6):
  if(d["e"][j]<50):
    print("Low Battery Alert")
  else:
    print("Battery Charge Normal")


Battery Charge Normal
Battery Charge Normal
Battery Charge Normal
Battery Charge Normal
Battery Charge Normal
Low Battery Alert


In [ ]:
def battery_status(charge):
  if(charge>70):
    return "High"
  elif(charge>=50 and charge<=70):
    return "Medium"
  else:
    return "Low"

for j in range(6):
  a=battery_status(d["e"][j])
  print(a)


High
High
High
Medium
Medium
Low


In [ ]:
import numpy as np
a= np.array([[32,400,20,95],
            [35,395,22,88],
            [38,390,25,80],
            [40,385,28,70],
            [42,380,30,60],
             [45,375,32,48]])
print(a)

[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]


In [ ]:
print("shape of matrix:",a.shape)

shape of matrix: (6, 5)


In [ ]:
add=0
for i in range(4):
  for j in range(6):
    add+=a[j][i]
  print(add/6)

38.666666666666664
426.1666666666667
452.3333333333333
525.8333333333334


In [ ]:
t_max=a[0][0]
t_min=a[0][0]
for i in range(6):
  if(a[i][0]>t_max):
    t_max=a[i][0]
  if(t_min>a[i][0]):
    t_min=a[i][0]
print("Max temp:",t_max)
print("Min temp:",t_min)

Max temp: 45
Min temp: 32


In [ ]:
b=np.zeros((6,1))
for i in range(6):
  b[i][0]=a[i][1]
print(b)


[[400.]
 [395.]
 [390.]
 [385.]
 [380.]
 [375.]]


In [ ]:
for i in range(6):
  if(a[i][0]>40):
    print("row:",i+1,"temp:",a[i][0])

row: 5 temp: 42
row: 6 temp: 45


In [ ]:
for i in range(6):
  if(a[i][3]<50):
    print("row:",i+1,"Charge:",a[i][3])

row: 6 Charge: 48


In [ ]:
A=np.array([[2,1],
            [1,3]])
print("Transpose:",A.T)

Transpose: [[2 1]
 [1 3]]


In [ ]:
print(np.linalg.det(A))

5.000000000000001


In [ ]:
print(np.linalg.inv(A))

[[ 0.6 -0.2]
 [-0.2  0.4]]


In [ ]:
X=np.array([[x],
           [y]])
B=np.array([[100],
            [120]])