In [ ]:
import numpy as np
a=np.array([1,2,4])
print(a)

[1 2 4]


In [ ]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr=np.arange(6,9)
print(arr)

[6 7 8]


In [ ]:
arr=np.arange(1,15)
print(arr.reshape(2,7))


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
arr=np.arange(6,18)
print(arr.shape)
print(arr.size)

(12,)
12


In [ ]:
arr=np.linspace(1,10,5,endpoint="false")
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.full((3, 3),9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(2, 3)
2
6
int64
[[10 40]
 [20 50]
 [30 60]]


In [ ]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr)
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # (Layers, Rows, Columns)
print(arr.size)   # Total number of elements
print(arr[0])        # First layer
print(arr[1])        # Second layer
print(arr[0][1])     # Second row of first layer
print(arr[1][0][0])  # Element 9

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[4 5 6]
7


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,1,4)
print(new_arr_3d)

[[[1 2 3 4]]

 [[5 6 7 8]]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[:4])
print(arr[1:5])
print(arr[:])
print(arr[1:6:2])
print(arr[::3])

[1 2 3 4]
[2 3 4 5]
[1 2 3 4 5 6]
[2 4 6]
[1 4]


In [ ]:
import numpy as np
arr=np.array([
    [[1,2,3],[2,3,4]],
    [[1,5,6],[1,4,8]]
])
#print(arr[1::])
#print(arr[::])
print(arr[0:8:1])
print(arr.shape)

[[[1 2 3]
  [2 3 4]]

 [[1 5 6]
  [1 4 8]]]
(2, 2, 3)


In [ ]:
import numpy as np

a = np.array([[10,20,30],[10,40,60]])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [[12 24 35]
 [12 44 65]]
Subtraction: [[ 8 16 25]
 [ 8 36 55]]
Multiplication: [[ 20  80 150]
 [ 20 160 300]]
Division: [[ 5.  5.  6.]
 [ 5. 10. 12.]]
Floor Division: [[ 5  5  6]
 [ 5 10 12]]
Modulus: [[0 0 0]
 [0 0 0]]
Power: [[ 100  400  900]
 [ 100 1600 3600]]


In [ ]:
import numpy as np

arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", arr)

print("\nSquare Root:", np.sqrt(arr))

print("Square:", np.square(arr))

print("Cube:", np.power(arr, 3))

arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))

print("\nExponential:", np.exp(arr))

print("\nNatural Log:", np.log(arr))

print("Log Base 10:", np.log10(arr))

print("\nSine:", np.sin(arr))

print("Cosine:", np.cos(arr))

print("Tangent:", np.tan(arr))

decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))

print("Ceiling:", np.ceil(decimal))

print("Floor:", np.floor(decimal))

Original Array: [ 1  4  9 16 25]

Square Root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Cube: [    1    64   729  4096 15625]

Absolute Value: [ 5 10 15 20 25]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Natural Log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log Base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]

Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tangent: [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [ ]:
import numpy as np


marks = np.array([75, 82, 90, 68, 95, 88, 79])

print("Original Array:", marks)

print("Sorted Array:", np.sort(marks))

print("\nSum:", np.sum(marks))

print("Mean:", np.mean(marks))

print("Median:", np.median(marks))


print("Maximum:", np.max(marks))

print("Minimum:", np.min(marks))


print("Range:", np.ptp(marks))

print("Standard Deviation:", np.std(marks))


print("Variance:", np.var(marks))

print("Index of Maximum:", np.argmax(marks))


print("Index of Minimum:", np.argmin(marks))

print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))


Original Array: [75 82 90 68 95 88 79]
Sorted Array: [68 75 79 82 88 90 95]

Sum: 577
Mean: 82.42857142857143
Median: 82.0
Maximum: 95
Minimum: 68
Range: 27
Standard Deviation: 8.633111388421788
Variance: 74.53061224489797
Index of Maximum: 4
Index of Minimum: 3
25th Percentile: 77.0
50th Percentile: 82.0
75th Percentile: 89.0


In [ ]:
print(5|3)

7


In [ ]:
x=17
x//=3
print(x)

5
